# Generated by Django 5.2 on 2025-04-11 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_opensolarbattery_opensolarinverter_opensolarmodule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opensolarbattery',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='opensolarinverter',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='opensolarmodule',
            name='proposal',
        ),
        migrations.AddField(
            model_name='opensolarbattery',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='api.opensolarproject'),
        ),
        migrations.AddField(
            model_name='opensolarinverter',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inverters', to='api.opensolarproject'),
        ),
        migrations.AddField(
            model_name='opensolarmodule',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.opensolarproject'),
        ),
    ]
