# Generated by Django 5.2 on 2025-04-11 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_opensolarproposal_online_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opensolarproposal',
            old_name='online_url',
            new_name='proposal_link',
        ),
        migrations.AlterField(
            model_name='opensolarbattery',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='api.opensolarproject'),
        ),
        migrations.AlterField(
            model_name='opensolarinverter',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='inverters', to='api.opensolarproject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opensolarmodule',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.opensolarproject'),
            preserve_default=False,
        ),
    ]
