# Generated by Django 5.2 on 2025-04-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_odooproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OdooProject',
        ),
    ]
