# Generated by Django 5.2 on 2025-05-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_opensolarsalesrep'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenSolarSalesRep',
            new_name='OpenSolarAssignedTeamMember',
        ),
    ]
