# Generated by Django 5.2 on 2025-05-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_opensolarproject_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensolarproject',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
