# Generated by Django 5.2 on 2025-05-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_opensolarproject_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opensolarproject',
            old_name='price_including_tax',
            new_name='price',
        ),
    ]
