# Generated by Django 5.2 on 2025-05-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_price_including_tax_opensolarproject_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensolarproject',
            name='price_excluding_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='opensolarproject',
            name='price_including_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
