# Generated by Django 5.2 on 2025-04-10 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_opensolarproposal_battery_size_kwh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opensolarproject',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.opensolarcustomer'),
        ),
    ]
