# Generated by Django 5.2 on 2025-04-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_opensolarproject_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensolarproject',
            name='battery_size_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='opensolarproject',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='opensolarproject',
            name='share_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opensolarproject',
            name='system_output_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='opensolarproject',
            name='system_size_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
