# Generated by Django 5.2 on 2025-04-11 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_opensolarproject_system_output_kwh'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSolarBattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='api.opensolarproposal')),
            ],
        ),
        migrations.CreateModel(
            name='OpenSolarInverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inverters', to='api.opensolarproposal')),
            ],
        ),
        migrations.CreateModel(
            name='OpenSolarModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.opensolarproposal')),
            ],
        ),
    ]
