# Generated by Django 5.2 on 2025-05-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_odooproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSolarSalesRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('schedule_meeting_url', models.URLField(blank=True)),
            ],
        ),
    ]
