# Generated by Django 5.2 on 2025-05-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_delete_opensolarassignedteammember_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opensolarproject',
            name='price',
        ),
        migrations.RemoveField(
            model_name='opensolarproject',
            name='price_excluding_tax',
        ),
    ]
