# Generated by Django 5.2 on 2025-05-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_opensolarproject_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opensolarproject',
            name='price',
        ),
    ]
